version: '2'
services:
  app:
    command: npm run dev
    volumes:
      - ./backend/src:/usr/crypto_buy/src
      - ./backend/config/app_dev.json:/usr/crypto_buy/build/config/app_dev.json:ro
      - ./backend/package.json:/usr/crypto_buy/package.json:ro          
    ports: ["56745:56745"]
    environment:      
      - NODE_ENV=dev

  # frontend:
  #   command: npm run dev
  #   volumes:
  #     - ./frontend/config:/usr/crypto_buy/frontend/config
  #     - ./frontend/public:/usr/crypto_buy/frontend/public
  #     - ./frontend/scripts:/usr/crypto_buy/frontend/scripts
  #     - ./frontend/src:/usr/crypto_buy/frontend/src
  #     - ./frontend/package.json:/usr/crypto_buy/frontend/package.json
  #     - ./frontend/webpack.config.json:/usr/crypto_buy/frontend/webpack.config.json
  #     - ./frontend/frontend.json:/usr/crypto_buy/frontend/frontend.json