version: '2'
services:
  mongo:
    image: mongo
    volumes:
      - volume_database:/data/db
    ports: ["127.0.0.1:27017:27017"]
    environment:
      - MONGO_PORT_27017_TCP_ADDR=127.0.0.1
  app:
    build:
      context: ./backend
    ports: ["5000:5000"]
    depends_on:      
      - mongo
    environment:
      - NODE_ENV=production     

  # frontend:
  #   build:
  #     context: ./frontend
  #   ports: ["3000:3000"]


volumes:
  volume_database:
    external: true